### ISSUE TITLE
Error oAuth Plugin not started

### ISSUE THREAD

**Issue by hejsiri** [maintux/homebridge-shelly-blu#1]
I installed the plugin, entered my account login information, but the plugin does not start. What could be the cause?

```
 [25/11/2023, 19:45:44] Error: Get Auth Code failed. Errors: %j[object Object]
     at ShellyCloudApi._getAuthCode (/var/lib/homebridge/node_modules/homebridge-shelly-blu/src/oauth.ts:50:15)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
     at /var/lib/homebridge/node_modules/homebridge-shelly-blu/src/oauth.ts:65:7
```

**Comment by hejsiri** [comment]
Problem solved, the error was idiotic.  Wrong password for Shelly Cloud :) Close sensors and light sensors have appeared as accessories, but the state of the sensors does not change.

**Comment by ChandlerHooley** [comment]
You have to update to NodeJS v 20 for it to not freeze up like that.
